export const TOUR_HOME_PAGE = "Tour Home Page";
export const CONNECTING_PAGE = "Connecting page";
export const CONNECTED_PAGE = "Connected page";
export const TOUR_START_PAGE = "Tour Start Page";
export const GO_TO_TOUR_PAGE = "Go To Tour Page";
export const TOUR_PLAY_PAGE = "Tour Play Page";
export const TOUR_PAUSE_PAGE = "Tour Pause Page";
export const TOUR_STOP_PAGE = "Tour Stop Page";
export const WELCOME_PAGE = "Welcome page";

export const HOME_TOURS = [
  {
    name: "Secret",
    type: "For Sale and charter",
    info: {
      length: "82.5m (270.6ft)",
      year: 2013,
      content: "Abeking & Rasmussen, 12 guests",
    },
    imgUrl: "./../../../assets/images/left-back1.png",
  },
  {
    name: "Hasna",
    type: "For Sale",
    info: {
      length: "73m (239.5ft)",
      year: 2017,
      content: "Feadship, 12 guests",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
  {
    name: "Barbara",
    type: "For Sale and charter",
    info: {
      length: "88.5m (290.4ft)",
      year: 2017,
      content: "Oceanco, 12 guests",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
  {
    name: "Anna I",
    type: "For Sale",
    info: {
      length: "67m (219.8ft)",
      year: 2007,
      content: "Feadship, De Vries",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
  {
    name: "Lady Christine",
    type: "For Sale",
    info: {
      length: "68m (223.1ft)",
      year: 2010,
      content: "Feadship, Royal Van Lent",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
  {
    name: "Inception",
    type: "For Sale",
    info: {
      length: "50m (164ft)",
      year: 2008,
      content: "Heesen",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
  {
    name: "Bash",
    type: "For Sale",
    info: {
      length: "56m (183.7ft)",
      year: 2012,
      content: "Benetti",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
  {
    name: "Ribelle",
    type: "For Sale",
    info: {
      length: "32.6m (106.9ft)",
      year: 2017,
      content: "Vitters",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
  {
    name: "Slipstream",
    type: "For charter",
    info: {
      length: "60m (196.9ft)",
      year: 2009,
      content: "CMN Shipyard, 12 guests",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
  {
    name: "Odyssey",
    type: "For Sale",
    info: {
      length: "40.2m (131.9ft)",
      year: 2015,
      content: "Princess Yachts International",
    },
    imgUrl: "../../../assets/images/SECRET.svg",
  },
];

export const TOURS = [
  {
    id: "1",
    status: "Pending",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "2",
    status: "Pending",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "3",
    status: "Connected",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "4",
    status: "Connected",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "5",
    status: "Available",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "6",
    status: "Available",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "7",
    status: "Unavailable",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "8",
    status: "Unavailable",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "9",
    status: "Complete",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "10",
    status: "Complete",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "11",
    status: "Complete",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "12",
    status: "Complete",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "13",
    status: "Complete",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "14",
    status: "Complete",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "15",
    status: "Complete",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "16",
    status: "Complete",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "16",
    status: "Complete",
    broker: "Tim Vickers",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
  {
    id: "17",
    status: "Complete",
    broker: "James Smith",
    client: "Pending",
    email: "",
    telephone: "",
    name: "HASANA",
    date: "",
  },
];
